// Pool de recettes réutilisées sur la semaine (3 options proposées par repas/jour).
// ratio: déclinaison du "bol Maju" — 1/2 légumes, 1/4 protéines, 1/4 féculents pour
// déjeuner/dîner ; au petit-déj le ratio est adapté (protéines + fibres + bon gras).

const RAYONS = {
  FL: "Fruits & légumes",
  VPO: "Viandes, poissons & œufs",
  CREM: "Crèmerie",
  EPI: "Épicerie",
  SURG: "Surgelés",
  EPICES: "Épices & condiments",
  BOUL: "Boulangerie",
};

function ing(name, rayon, qtyPerPerson, unit) {
  return { name, rayon, qtyPerPerson, unit };
}

const recipes = [
  // ---------- PETIT-DÉJEUNERS ----------
  {
    id: "oeufs-brouilles-avocat",
    name: "Œufs brouillés minute & tartine d'avocat",
    mealType: "petit-dej",
    prepMinutes: 10,
    weekendOnly: false,
    ratio: "Protéines + bon gras + fibres",
    tags: ["proteines-matin"],
    spices: ["paprika fumé", "poivre"],
    steps: [
      "Battre les œufs, cuire 3 min à feu doux en remuant.",
      "Griller le pain, écraser l'avocat dessus avec un filet de citron.",
      "Déposer les œufs sur la tartine, saupoudrer de paprika fumé, graines de sésame, sel et poivre.",
    ],
    ingredients: [
      ing("Œufs", RAYONS.VPO, 2, "unité"),
      ing("Pain complet", RAYONS.BOUL, 2, "tranche"),
      ing("Avocat", RAYONS.FL, 0.5, "unité"),
      ing("Citron", RAYONS.FL, 0.2, "unité"),
      ing("Graines de sésame", RAYONS.EPICES, 1, "càc"),
      ing("Paprika fumé", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "porridge-choco-noisette",
    name: "Porridge choco-noisette fer & magnésium",
    mealType: "petit-dej",
    prepMinutes: 8,
    weekendOnly: false,
    ratio: "Fibres + protéines + fer/magnésium",
    tags: ["fer-magnesium", "proteines-matin"],
    spices: ["cannelle"],
    steps: [
      "Faire chauffer le lait avec les flocons d'avoine 4-5 min en remuant.",
      "Ajouter le cacao non sucré et la cannelle hors du feu.",
      "Napper de purée de noisette, banane en rondelles et graines de chia.",
    ],
    ingredients: [
      ing("Flocons d'avoine", RAYONS.EPI, 50, "g"),
      ing("Lait (ou boisson végétale)", RAYONS.CREM, 200, "ml"),
      ing("Cacao non sucré", RAYONS.EPI, 1, "càs"),
      ing("Purée de noisette", RAYONS.EPI, 1, "càs"),
      ing("Banane", RAYONS.FL, 1, "unité"),
      ing("Graines de chia", RAYONS.EPICES, 1, "càc"),
      ing("Cannelle", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "yaourt-grec-granola",
    name: "Yaourt grec, fruits rouges & granola épicé",
    mealType: "petit-dej",
    prepMinutes: 5,
    weekendOnly: false,
    ratio: "Protéines + fibres + bon gras",
    tags: ["proteines-matin"],
    spices: ["cannelle"],
    steps: [
      "Verser le yaourt grec dans un bol.",
      "Ajouter les fruits rouges (surgelés décongelés ou frais).",
      "Parsemer de granola, amandes concassées et une pincée de cannelle.",
    ],
    ingredients: [
      ing("Yaourt grec", RAYONS.CREM, 150, "g"),
      ing("Fruits rouges surgelés", RAYONS.SURG, 80, "g"),
      ing("Granola", RAYONS.EPI, 30, "g"),
      ing("Amandes", RAYONS.EPI, 10, "g"),
      ing("Cannelle", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "tartine-avocat-oeuf-poche",
    name: "Tartine avocat, œuf poché & graines de lin",
    mealType: "petit-dej",
    prepMinutes: 12,
    weekendOnly: false,
    ratio: "Protéines + oméga-3 + fibres",
    tags: ["proteines-matin", "omega-3"],
    spices: ["poivre", "piment doux"],
    steps: [
      "Pocher l'œuf 3 min dans une eau frémissante avec un trait de vinaigre.",
      "Écraser l'avocat sur le pain grillé, saler, poivrer.",
      "Déposer l'œuf poché dessus, saupoudrer de graines de lin et piment doux.",
    ],
    ingredients: [
      ing("Œufs", RAYONS.VPO, 1, "unité"),
      ing("Pain complet", RAYONS.BOUL, 2, "tranche"),
      ing("Avocat", RAYONS.FL, 0.5, "unité"),
      ing("Graines de lin", RAYONS.EPICES, 1, "càc"),
      ing("Piment doux", RAYONS.EPICES, 1, "pincée"),
      ing("Vinaigre", RAYONS.EPI, 1, "càc"),
    ],
  },
  {
    id: "smoothie-bowl-proteine",
    name: "Smoothie bowl protéiné banane-cacahuète",
    mealType: "petit-dej",
    prepMinutes: 7,
    weekendOnly: false,
    ratio: "Protéines + fer/magnésium + fibres",
    tags: ["proteines-matin", "fer-magnesium"],
    spices: ["cacao"],
    steps: [
      "Mixer banane, skyr, beurre de cacahuète et flocons d'avoine.",
      "Verser dans un bol.",
      "Décorer de cacao non sucré et graines de courge.",
    ],
    ingredients: [
      ing("Banane", RAYONS.FL, 1, "unité"),
      ing("Skyr ou yaourt grec", RAYONS.CREM, 150, "g"),
      ing("Beurre de cacahuète", RAYONS.EPI, 1, "càs"),
      ing("Flocons d'avoine", RAYONS.EPI, 30, "g"),
      ing("Graines de courge", RAYONS.EPICES, 1, "càc"),
      ing("Cacao non sucré", RAYONS.EPI, 1, "càc"),
    ],
  },
  {
    id: "pain-perdu-sale",
    name: "Pain perdu salé fromage & épinards",
    mealType: "petit-dej",
    prepMinutes: 12,
    weekendOnly: false,
    ratio: "Protéines + fer + féculents",
    tags: ["proteines-matin", "fer-magnesium"],
    spices: ["muscade", "poivre"],
    steps: [
      "Fouetter œuf, lait, muscade et poivre. Y tremper le pain rassis.",
      "Faire revenir les épinards 2 min à la poêle.",
      "Cuire le pain à la poêle 2 min par face, garnir d'épinards et fromage râpé fondu.",
    ],
    ingredients: [
      ing("Pain rassis", RAYONS.BOUL, 2, "tranche"),
      ing("Œufs", RAYONS.VPO, 1, "unité"),
      ing("Lait", RAYONS.CREM, 50, "ml"),
      ing("Épinards frais", RAYONS.FL, 50, "g"),
      ing("Fromage râpé", RAYONS.CREM, 30, "g"),
      ing("Muscade", RAYONS.EPICES, 1, "pincée"),
    ],
  },

  // ---------- DÉJEUNERS ----------
  {
    id: "bol-poulet-cumin-legumes-rotis",
    name: "Bol de riz, poulet mariné cumin-paprika & légumes rôtis",
    mealType: "dejeuner",
    prepMinutes: 25,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: [],
    spices: ["cumin", "paprika", "ail"],
    steps: [
      "Mariner le poulet coupé en dés avec cumin, paprika, ail et huile d'olive.",
      "Cuire riz complet selon paquet. Rôtir courgette et poivron au four ou à la poêle.",
      "Saisir le poulet 6-8 min. Dresser en bol avec un filet de citron.",
    ],
    ingredients: [
      ing("Riz complet", RAYONS.EPI, 60, "g"),
      ing("Blanc de poulet", RAYONS.VPO, 120, "g"),
      ing("Courgette", RAYONS.FL, 100, "g"),
      ing("Poivron", RAYONS.FL, 100, "g"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Paprika", RAYONS.EPICES, 1, "càc"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Huile d'olive", RAYONS.EPI, 1, "càs"),
      ing("Citron", RAYONS.FL, 0.25, "unité"),
    ],
  },
  {
    id: "lentilles-corail-curry-epinards",
    name: "Lentilles corail au curry, épinards & riz",
    mealType: "dejeuner",
    prepMinutes: 20,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["curry", "gingembre", "ail"],
    steps: [
      "Faire revenir ail et gingembre, ajouter curry, lentilles corail et lait de coco léger + eau.",
      "Cuire 12-15 min à couvert jusqu'à ce que les lentilles fondent.",
      "Ajouter les épinards en fin de cuisson, servir avec riz complet.",
    ],
    ingredients: [
      ing("Lentilles corail", RAYONS.EPI, 70, "g"),
      ing("Épinards frais", RAYONS.FL, 100, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Lait de coco léger", RAYONS.EPI, 100, "ml"),
      ing("Curry", RAYONS.EPICES, 1, "càc"),
      ing("Gingembre frais", RAYONS.EPICES, 1, "càc"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
    ],
  },
  {
    id: "pates-completes-thon-tomates",
    name: "Pâtes complètes, thon, tomates cerises & olives",
    mealType: "dejeuner",
    prepMinutes: 18,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["omega-3"],
    spices: ["basilic", "ail"],
    steps: [
      "Cuire les pâtes complètes al dente.",
      "Poêler ail, tomates cerises coupées en deux et olives 5 min.",
      "Égoutter le thon, mélanger le tout, ajouter basilic et un filet d'huile d'olive.",
    ],
    ingredients: [
      ing("Pâtes complètes", RAYONS.EPI, 70, "g"),
      ing("Thon au naturel (boîte)", RAYONS.EPI, 1, "boîte"),
      ing("Tomates cerises", RAYONS.FL, 150, "g"),
      ing("Olives", RAYONS.EPI, 30, "g"),
      ing("Basilic frais", RAYONS.FL, 1, "brin"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Huile d'olive", RAYONS.EPI, 1, "càs"),
    ],
  },
  {
    id: "quinoa-pois-chiches-rotis",
    name: "Bol de quinoa, pois chiches rôtis épicés & crudités",
    mealType: "dejeuner",
    prepMinutes: 22,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["cumin", "paprika"],
    steps: [
      "Cuire le quinoa selon paquet.",
      "Rôtir les pois chiches à la poêle avec cumin et paprika 8-10 min.",
      "Râper carotte, trancher concombre, dresser le bol, napper de tahini-citron.",
    ],
    ingredients: [
      ing("Quinoa", RAYONS.EPI, 60, "g"),
      ing("Pois chiches (boîte)", RAYONS.EPI, 150, "g"),
      ing("Carotte", RAYONS.FL, 80, "g"),
      ing("Concombre", RAYONS.FL, 80, "g"),
      ing("Tahini", RAYONS.EPI, 1, "càs"),
      ing("Citron", RAYONS.FL, 0.25, "unité"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Paprika", RAYONS.EPICES, 1, "càc"),
    ],
  },
  {
    id: "wrap-dinde-houmous",
    name: "Wrap de dinde, houmous & crudités croquantes",
    mealType: "dejeuner",
    prepMinutes: 15,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: [],
    spices: ["paprika"],
    steps: [
      "Poêler l'escalope de dinde coupée en lanières avec paprika, 6-8 min.",
      "Tartiner la tortilla de houmous.",
      "Garnir de dinde, carotte râpée et chou rouge émincé, rouler.",
    ],
    ingredients: [
      ing("Tortilla complète", RAYONS.BOUL, 2, "unité"),
      ing("Escalope de dinde", RAYONS.VPO, 120, "g"),
      ing("Houmous", RAYONS.EPI, 60, "g"),
      ing("Carotte", RAYONS.FL, 60, "g"),
      ing("Chou rouge", RAYONS.FL, 60, "g"),
      ing("Paprika", RAYONS.EPICES, 1, "càc"),
    ],
  },
  {
    id: "saumon-brocoli-riz",
    name: "Poêlée de saumon, brocoli vapeur & riz complet",
    mealType: "dejeuner",
    prepMinutes: 20,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["omega-3"],
    spices: ["aneth", "ail"],
    steps: [
      "Cuire le riz complet et le brocoli à la vapeur.",
      "Saisir le pavé de saumon 3-4 min par face avec ail et aneth.",
      "Dresser avec un filet de citron.",
    ],
    ingredients: [
      ing("Pavé de saumon", RAYONS.VPO, 120, "g"),
      ing("Brocoli", RAYONS.FL, 150, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Citron", RAYONS.FL, 0.25, "unité"),
      ing("Aneth", RAYONS.EPICES, 1, "pincée"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
    ],
  },
  {
    id: "bol-texmex-haricots-rouges",
    name: "Bol tex-mex haricots rouges, maïs & avocat",
    mealType: "dejeuner",
    prepMinutes: 15,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["cumin", "paprika fumé"],
    steps: [
      "Réchauffer haricots rouges et maïs avec cumin et paprika fumé.",
      "Cuire le riz (ou réchauffer des tortillas).",
      "Dresser en bol avec avocat en dés et tomate fraîche.",
    ],
    ingredients: [
      ing("Haricots rouges (boîte)", RAYONS.EPI, 150, "g"),
      ing("Maïs (boîte)", RAYONS.EPI, 80, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Avocat", RAYONS.FL, 0.5, "unité"),
      ing("Tomate", RAYONS.FL, 100, "g"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Paprika fumé", RAYONS.EPICES, 1, "càc"),
    ],
  },
  {
    id: "curry-pois-chiches-patate-douce",
    name: "Curry de pois chiches & patate douce mijoté",
    mealType: "dejeuner",
    prepMinutes: 40,
    weekendOnly: true,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["curry", "gingembre", "coriandre"],
    steps: [
      "Faire revenir oignon, ail, gingembre et curry.",
      "Ajouter patate douce en dés, pois chiches et lait de coco, mijoter 25 min.",
      "Servir sur riz basmati, parsemer de coriandre fraîche.",
    ],
    ingredients: [
      ing("Patate douce", RAYONS.FL, 150, "g"),
      ing("Pois chiches (boîte)", RAYONS.EPI, 150, "g"),
      ing("Lait de coco", RAYONS.EPI, 150, "ml"),
      ing("Riz basmati", RAYONS.EPI, 60, "g"),
      ing("Oignon", RAYONS.FL, 0.5, "unité"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Gingembre frais", RAYONS.EPICES, 1, "càc"),
      ing("Curry", RAYONS.EPICES, 1, "càs"),
      ing("Coriandre fraîche", RAYONS.FL, 1, "brin"),
    ],
  },
  {
    id: "poulet-roti-legumes-racines",
    name: "Poulet rôti aux épices, légumes racines au four",
    mealType: "dejeuner",
    prepMinutes: 45,
    weekendOnly: true,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: [],
    spices: ["romarin", "paprika", "cumin"],
    steps: [
      "Frotter les cuisses de poulet avec ail, paprika, cumin et romarin.",
      "Couper carotte et panais en morceaux, enfourner le tout 35-40 min à 200°C.",
      "Vérifier la cuisson du poulet avant de servir.",
    ],
    ingredients: [
      ing("Cuisses de poulet", RAYONS.VPO, 180, "g"),
      ing("Carotte", RAYONS.FL, 120, "g"),
      ing("Panais ou pomme de terre", RAYONS.FL, 120, "g"),
      ing("Ail", RAYONS.FL, 2, "gousse"),
      ing("Romarin", RAYONS.EPICES, 1, "brin"),
      ing("Paprika", RAYONS.EPICES, 1, "càc"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Huile d'olive", RAYONS.EPI, 1, "càs"),
    ],
  },

  // ---------- DÎNERS ----------
  {
    id: "dinde-poivrons-riz-paprika",
    name: "Poêlée de dinde, poivrons & riz complet au paprika",
    mealType: "diner",
    prepMinutes: 20,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: [],
    spices: ["paprika", "ail"],
    steps: [
      "Cuire le riz complet.",
      "Poêler l'escalope de dinde en lanières avec ail et paprika.",
      "Ajouter les poivrons émincés, cuire 6-8 min, servir sur le riz.",
    ],
    ingredients: [
      ing("Escalope de dinde", RAYONS.VPO, 120, "g"),
      ing("Poivron", RAYONS.FL, 150, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Paprika", RAYONS.EPICES, 1, "càc"),
    ],
  },
  {
    id: "soupe-lentilles-corail-carotte",
    name: "Soupe-repas lentilles corail, carotte & cumin",
    mealType: "diner",
    prepMinutes: 20,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["cumin", "ail"],
    steps: [
      "Faire revenir oignon, ail et cumin.",
      "Ajouter carotte en rondelles, lentilles corail et bouillon, cuire 15 min.",
      "Mixer grossièrement ou servir tel quel avec du pain complet.",
    ],
    ingredients: [
      ing("Lentilles corail", RAYONS.EPI, 60, "g"),
      ing("Carotte", RAYONS.FL, 150, "g"),
      ing("Oignon", RAYONS.FL, 0.5, "unité"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Pain complet", RAYONS.BOUL, 1, "tranche"),
    ],
  },
  {
    id: "oeufs-poches-epinards-patate-douce",
    name: "Œufs pochés, épinards & patate douce rôtie",
    mealType: "diner",
    prepMinutes: 25,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["muscade", "poivre"],
    steps: [
      "Rôtir la patate douce en dés au four ou à la poêle 15-18 min.",
      "Poêler les épinards avec une pointe de muscade.",
      "Pocher les œufs 3 min, dresser le tout ensemble.",
    ],
    ingredients: [
      ing("Œufs", RAYONS.VPO, 2, "unité"),
      ing("Épinards frais", RAYONS.FL, 120, "g"),
      ing("Patate douce", RAYONS.FL, 150, "g"),
      ing("Muscade", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "saute-poulet-brocoli-nouilles-sesame",
    name: "Sauté de poulet, brocoli & nouilles sésame-gingembre",
    mealType: "diner",
    prepMinutes: 20,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: [],
    spices: ["gingembre", "sésame"],
    steps: [
      "Cuire les nouilles selon paquet.",
      "Faire sauter le poulet en dés avec gingembre 5 min, ajouter le brocoli 5 min.",
      "Mélanger aux nouilles, sauce soja et graines de sésame.",
    ],
    ingredients: [
      ing("Blanc de poulet", RAYONS.VPO, 120, "g"),
      ing("Brocoli", RAYONS.FL, 150, "g"),
      ing("Nouilles asiatiques", RAYONS.EPI, 70, "g"),
      ing("Gingembre frais", RAYONS.EPICES, 1, "càc"),
      ing("Graines de sésame", RAYONS.EPICES, 1, "càc"),
      ing("Sauce soja", RAYONS.EPI, 1, "càs"),
    ],
  },
  {
    id: "cabillaud-brocoli-quinoa",
    name: "Cabillaud vapeur, purée de brocoli & quinoa citron",
    mealType: "diner",
    prepMinutes: 22,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["omega-3"],
    spices: ["aneth"],
    steps: [
      "Cuire le quinoa selon paquet, zester un peu de citron dedans.",
      "Cuire le cabillaud et le brocoli à la vapeur 10-12 min.",
      "Écraser grossièrement le brocoli, dresser avec aneth et citron.",
    ],
    ingredients: [
      ing("Filet de cabillaud", RAYONS.VPO, 130, "g"),
      ing("Brocoli", RAYONS.FL, 150, "g"),
      ing("Quinoa", RAYONS.EPI, 50, "g"),
      ing("Citron", RAYONS.FL, 0.25, "unité"),
      ing("Aneth", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "chili-sin-carne",
    name: "Chili sin carne haricots rouges & maïs, riz complet",
    mealType: "diner",
    prepMinutes: 25,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines végétales • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["cumin", "paprika fumé", "piment"],
    steps: [
      "Faire revenir oignon, ail, cumin, paprika fumé et piment.",
      "Ajouter tomates concassées, haricots rouges et maïs, mijoter 15 min.",
      "Servir avec riz complet.",
    ],
    ingredients: [
      ing("Haricots rouges (boîte)", RAYONS.EPI, 150, "g"),
      ing("Maïs (boîte)", RAYONS.EPI, 80, "g"),
      ing("Tomates concassées (boîte)", RAYONS.EPI, 200, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Oignon", RAYONS.FL, 0.5, "unité"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Paprika fumé", RAYONS.EPICES, 1, "càc"),
      ing("Piment doux", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "crevettes-ail-courgettes-riz",
    name: "Poêlée de crevettes à l'ail, courgettes & riz complet",
    mealType: "diner",
    prepMinutes: 18,
    weekendOnly: false,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["omega-3"],
    spices: ["ail", "persil", "piment doux"],
    steps: [
      "Cuire le riz complet.",
      "Poêler les courgettes en rondelles 5 min.",
      "Ajouter les crevettes, ail et piment doux, cuire 3-4 min, parsemer de persil.",
    ],
    ingredients: [
      ing("Crevettes décortiquées", RAYONS.VPO, 120, "g"),
      ing("Courgette", RAYONS.FL, 150, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Ail", RAYONS.FL, 2, "gousse"),
      ing("Persil frais", RAYONS.FL, 1, "brin"),
      ing("Piment doux", RAYONS.EPICES, 1, "pincée"),
    ],
  },
  {
    id: "papillote-saumon-herbes",
    name: "Papillote de saumon aux herbes, légumes de saison & riz",
    mealType: "diner",
    prepMinutes: 40,
    weekendOnly: true,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["omega-3"],
    spices: ["aneth", "persil", "citron"],
    steps: [
      "Disposer saumon, courgette et carotte en fines lamelles dans une papillote avec herbes et citron.",
      "Cuire 25 min au four à 190°C.",
      "Servir avec riz complet.",
    ],
    ingredients: [
      ing("Pavé de saumon", RAYONS.VPO, 130, "g"),
      ing("Courgette", RAYONS.FL, 100, "g"),
      ing("Carotte", RAYONS.FL, 100, "g"),
      ing("Riz complet", RAYONS.EPI, 60, "g"),
      ing("Citron", RAYONS.FL, 0.25, "unité"),
      ing("Aneth", RAYONS.EPICES, 1, "pincée"),
      ing("Persil frais", RAYONS.FL, 1, "brin"),
    ],
  },
  {
    id: "chili-con-carne-mijote",
    name: "Chili con carne mijoté, riz complet & avocat",
    mealType: "diner",
    prepMinutes: 45,
    weekendOnly: true,
    ratio: "1/2 légumes • 1/4 protéines • 1/4 féculents",
    tags: ["fer-magnesium"],
    spices: ["cumin", "paprika fumé", "piment"],
    steps: [
      "Faire revenir bœuf haché, oignon et ail avec les épices.",
      "Ajouter tomates concassées et haricots rouges, mijoter 30 min à couvert.",
      "Servir avec riz complet et avocat en dés — idéal à préparer en double pour le lendemain midi.",
    ],
    ingredients: [
      ing("Bœuf haché 5%", RAYONS.VPO, 120, "g"),
      ing("Haricots rouges (boîte)", RAYONS.EPI, 150, "g"),
      ing("Tomates concassées (boîte)", RAYONS.EPI, 200, "g"),
      ing("Riz complet", RAYONS.EPI, 50, "g"),
      ing("Avocat", RAYONS.FL, 0.5, "unité"),
      ing("Oignon", RAYONS.FL, 0.5, "unité"),
      ing("Ail", RAYONS.FL, 1, "gousse"),
      ing("Cumin", RAYONS.EPICES, 1, "càc"),
      ing("Paprika fumé", RAYONS.EPICES, 1, "càc"),
      ing("Piment doux", RAYONS.EPICES, 1, "pincée"),
    ],
  },
];

module.exports = { recipes, RAYONS };
